/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.arena;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.arena.FrameBuilder;
import net.virtualinfinity.atrobots.snapshots.ArenaObjectSnapshot;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class FrameBuilderEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      FrameBuilder frameBuilder0 = new FrameBuilder();
      frameBuilder0.beginFrame(true);
  }

  @Test
  public void test1()  throws Throwable  {
      FrameBuilder frameBuilder0 = new FrameBuilder();
      frameBuilder0.endFrame();
  }

  @Test
  public void test2()  throws Throwable  {
      FrameBuilder frameBuilder0 = new FrameBuilder();
      // Undeclared exception!
      try {
        frameBuilder0.addObject((ArenaObjectSnapshot) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
