/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.arena;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.arena.LinearDamageFunction;
import net.virtualinfinity.atrobots.arena.Position;
import net.virtualinfinity.atrobots.arena.TangibleArenaObject;
import net.virtualinfinity.atrobots.arenaobjects.DamageInflicter;
import net.virtualinfinity.atrobots.hardware.mines.Mine;
import net.virtualinfinity.atrobots.robot.Robot;
import net.virtualinfinity.atrobots.robot.RobotScore;
import net.virtualinfinity.atrobots.robot.RobotScoreKeeper;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class LinearDamageFunctionEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Robot robot0 = new Robot("l", (-1691), (RobotScore) null);
      Position position0 = robot0.getPosition();
      LinearDamageFunction linearDamageFunction0 = new LinearDamageFunction(position0, 1500.0, 0.0);
      // Undeclared exception!
      try {
        linearDamageFunction0.inflictDamage((DamageInflicter) robot0, (TangibleArenaObject) robot0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("", 647, (RobotScore) robotScoreKeeper0);
      Mine mine0 = new Mine((DamageInflicter) robot0);
      Position position0 = mine0.getPosition();
      LinearDamageFunction linearDamageFunction0 = new LinearDamageFunction(position0, (double) 0, 0.0);
      double double0 = linearDamageFunction0.getRadius();
      assertEquals(0.0, double0, 0.01D);
  }

  @Test
  public void test2()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("", 647, (RobotScore) robotScoreKeeper0);
      Mine mine0 = new Mine((DamageInflicter) robot0);
      Position position0 = mine0.getPosition();
      LinearDamageFunction linearDamageFunction0 = new LinearDamageFunction(position0, (double) 0, 0.0);
      linearDamageFunction0.getCenter();
      assertEquals(0.0, linearDamageFunction0.getRadius(), 0.01D);
  }
}
