/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.arena;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.arena.Odometer;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class OdometerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Odometer odometer0 = new Odometer();
      odometer0.setDistance(0.0);
      assertEquals(0.0, odometer0.getDistance(), 0.01D);
  }

  @Test
  public void test1()  throws Throwable  {
      Odometer odometer0 = new Odometer();
      odometer0.accumulate(1.0);
      assertEquals(1.0, odometer0.getDistance(), 0.01D);
  }

  @Test
  public void test2()  throws Throwable  {
      Odometer odometer0 = new Odometer();
      odometer0.reset();
      assertEquals(0.0, odometer0.getDistance(), 0.01D);
  }

  @Test
  public void test3()  throws Throwable  {
      Odometer odometer0 = new Odometer();
      double double0 = odometer0.getDistance();
      assertEquals(0.0, double0, 0.01D);
  }
}
