/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.arena;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.arena.Odometer;
import net.virtualinfinity.atrobots.arena.Position;
import net.virtualinfinity.atrobots.measures.Vector;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class PositionEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Position position0 = new Position();
      // Undeclared exception!
      try {
        position0.getVectorTo(position0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      Position position0 = new Position();
      Vector vector0 = position0.getVector();
      assertNull(vector0);
  }

  @Test
  public void test2()  throws Throwable  {
      Position position0 = new Position((Vector) null);
      assertNotNull(position0);
  }

  @Test
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try {
        Position.random((-14.858829744607219), (-14.858829744607219), 1894.1189864455328, 1894.1189864455328);
        fail("Expecting exception: NoSuchMethodError");
      } catch(NoSuchMethodError e) {
        /*
         * org.evosuite.runtime.Random.nextDouble()D
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      Position position0 = new Position();
      // Undeclared exception!
      try {
        position0.getY();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test5()  throws Throwable  {
      Position position0 = new Position();
      position0.copyFrom(position0);
  }

  @Test
  public void test6()  throws Throwable  {
      Position position0 = new Position();
      // Undeclared exception!
      try {
        position0.move((Vector) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test7()  throws Throwable  {
      Position position0 = new Position();
      Odometer odometer0 = new Odometer();
      position0.setOdometer(odometer0);
      // Undeclared exception!
      try {
        position0.move((Vector) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
