/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.arena;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.arena.SimulationFrame;
import net.virtualinfinity.atrobots.arena.SimulationFrameBuffer;
import net.virtualinfinity.atrobots.arena.SimulationObserver;
import net.virtualinfinity.atrobots.gui.RobotStatusPane;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class SimulationFrameBufferEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SimulationFrameBuffer simulationFrameBuffer0 = new SimulationFrameBuffer();
      SimulationFrame simulationFrame0 = simulationFrameBuffer0.getCurrentFrame();
      assertNull(simulationFrame0);
  }

  @Test
  public void test1()  throws Throwable  {
      SimulationFrameBuffer simulationFrameBuffer0 = new SimulationFrameBuffer();
      RobotStatusPane robotStatusPane0 = RobotStatusPane.createRobotStatusPane();
      simulationFrameBuffer0.removeSimulationObserver((SimulationObserver) robotStatusPane0);
      assertEquals(-1, robotStatusPane0.getSelectedIndex());
  }

  @Test
  public void test2()  throws Throwable  {
      SimulationFrameBuffer simulationFrameBuffer0 = new SimulationFrameBuffer();
      RobotStatusPane robotStatusPane0 = RobotStatusPane.createRobotStatusPane();
      simulationFrameBuffer0.addSimulationObserver((SimulationObserver) robotStatusPane0);
      simulationFrameBuffer0.setFrame((SimulationFrame) null);
  }
}
