/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.arena;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.arena.Speed;
import net.virtualinfinity.atrobots.measures.Duration;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class SpeedEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Speed speed0 = new Speed();
      assertEquals("0.0/1s", speed0.toString());
      
      speed0.setDistanceOverTime(0.0, (Duration) null);
      assertEquals("0.0/null", speed0.toString());
  }

  @Test
  public void test1()  throws Throwable  {
      Speed speed0 = new Speed();
      Duration duration0 = Duration.ONE_CYCLE;
      double double0 = speed0.times(duration0);
      assertEquals("0.0/1s", speed0.toString());
      assertEquals(0.0, double0, 0.01D);
  }

  @Test
  public void test2()  throws Throwable  {
      Speed speed0 = new Speed();
      String string0 = speed0.toString();
      assertEquals("0.0/1s", string0);
      assertNotNull(string0);
  }
}
