/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.arena;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.arena.Heading;
import net.virtualinfinity.atrobots.arena.Speed;
import net.virtualinfinity.atrobots.arena.Velocity;
import net.virtualinfinity.atrobots.measures.Duration;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class VelocityEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Speed speed0 = new Speed();
      Velocity velocity0 = new Velocity((Heading) null, speed0);
      Duration duration0 = Duration.ONE_CYCLE;
      // Undeclared exception!
      try {
        velocity0.times(duration0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      Heading heading0 = new Heading();
      Speed speed0 = new Speed();
      Velocity velocity0 = new Velocity(heading0, speed0);
      String string0 = velocity0.toString();
      assertEquals("0.3436116964863836r/78", heading0.toString());
      assertEquals("0.3436116964863836r/78*0.0/1s", string0);
  }
}
