/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.atsetup;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.util.Collection;
import net.virtualinfinity.atrobots.atsetup.AtRobotRegister;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class AtRobotRegisterEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      AtRobotRegister atRobotRegister0 = AtRobotRegister.SP;
      Collection<String> collection0 = atRobotRegister0.getSymbolNames();
      assertEquals(false, collection0.isEmpty());
  }

  @Test
  public void test1()  throws Throwable  {
      AtRobotRegister atRobotRegister0 = AtRobotRegister.METERS;
      int int0 = atRobotRegister0.getSymbolValue();
      assertEquals(9, int0);
  }
}
