/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.atsetup;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.util.Collection;
import net.virtualinfinity.atrobots.atsetup.AtRobotInterrupt;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class AtRobotInterruptEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      AtRobotInterrupt atRobotInterrupt0 = AtRobotInterrupt.DESTRUCT;
      Collection<String> collection0 = atRobotInterrupt0.getSymbolNames();
      assertEquals(1, collection0.size());
  }

  @Test
  public void test1()  throws Throwable  {
      AtRobotInterrupt atRobotInterrupt0 = AtRobotInterrupt.DESTRUCT;
      int int0 = atRobotInterrupt0.getSymbolValue();
      assertEquals(0, int0);
  }

  @Test
  public void test2()  throws Throwable  {
      String string0 = AtRobotInterrupt.nameOf((short) (-1143));
      assertEquals("<unknown>", string0);
      assertNotNull(string0);
  }

  @Test
  public void test3()  throws Throwable  {
      String string0 = AtRobotInterrupt.nameOf((short)0);
      assertEquals("I_DESTRUCT", string0);
      assertNotNull(string0);
  }

  @Test
  public void test4()  throws Throwable  {
      String string0 = AtRobotInterrupt.nameOf((short)1592);
      assertEquals("<unknown>", string0);
      assertNotNull(string0);
  }
}
