/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.atsetup;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.util.Collection;
import net.virtualinfinity.atrobots.atsetup.AtRobotInstruction;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class AtRobotInstructionEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      AtRobotInstruction atRobotInstruction0 = AtRobotInstruction.LOOP;
      Collection<String> collection0 = atRobotInstruction0.getSymbolNames();
      assertEquals(1, collection0.size());
  }

  @Test
  public void test1()  throws Throwable  {
      AtRobotInstruction atRobotInstruction0 = AtRobotInstruction.LOOP;
      int int0 = atRobotInstruction0.getSymbolValue();
      assertEquals(19, int0);
  }

  @Test
  public void test2()  throws Throwable  {
      String string0 = AtRobotInstruction.nameOf((short) (-1151));
      assertEquals("<unknown>", string0);
      assertNotNull(string0);
  }

  @Test
  public void test3()  throws Throwable  {
      String string0 = AtRobotInstruction.nameOf((short)256);
      assertEquals("<unknown>", string0);
      assertNotNull(string0);
  }

  @Test
  public void test4()  throws Throwable  {
      String string0 = AtRobotInstruction.nameOf((short)14);
      assertEquals("JGR", string0);
      assertNotNull(string0);
  }
}
