/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.atsetup;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.atsetup.AtRobotMicrocodes;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class AtRobotMicrocodesEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      AtRobotMicrocodes atRobotMicrocodes0 = new AtRobotMicrocodes();
  }
}
