/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.ports;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.ports.InvalidPort;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class InvalidPortEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      InvalidPort invalidPort0 = new InvalidPort();
  }
}
