/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.config;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import net.virtualinfinity.atrobots.config.RobotFile;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class RobotSourceEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      File file0 = new File("", "");
      RobotFile robotFile0 = new RobotFile(file0);
      String string0 = robotFile0.toString();
      assertEquals("", string0);
  }

  @Test
  public void test1()  throws Throwable  {
      File file0 = new File("", "");
      RobotFile robotFile0 = new RobotFile(file0);
      try {
        robotFile0.createFactory();
        fail("Expecting exception: FileNotFoundException");
      } catch(FileNotFoundException e) {
        /*
         * / (Is a directory)
         */
      }
  }
}
