/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.config;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import net.virtualinfinity.atrobots.compiler.AtRobotCompiler;
import net.virtualinfinity.atrobots.config.RobotFile;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class RobotFileEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      File file0 = new File("", "");
      RobotFile robotFile0 = new RobotFile(file0);
      assertNotNull(robotFile0);
      
      String string0 = robotFile0.getName();
      assertNotNull(string0);
      assertEquals("", string0);
  }

  @Test
  public void test1()  throws Throwable  {
      File file0 = new File("", "");
      RobotFile robotFile0 = new RobotFile(file0);
      assertNotNull(robotFile0);
      
      AtRobotCompiler atRobotCompiler0 = new AtRobotCompiler();
      try {
        robotFile0.compile(atRobotCompiler0);
        fail("Expecting exception: FileNotFoundException");
      } catch(FileNotFoundException e) {
        /*
         * / (Is a directory)
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      File file0 = new File("zitgun.at2");
      RobotFile robotFile0 = null;
      try {
        robotFile0 = new RobotFile(file0);
        fail("Expecting exception: FileNotFoundException");
      } catch(FileNotFoundException e) {
        /*
         * zitgun.at2
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      String string0 = RobotFile.removeEndIgnoreCase((String) null, (String) null);
      assertNull(string0);
  }

  @Test
  public void test4()  throws Throwable  {
      String string0 = RobotFile.removeEndIgnoreCase("", "");
      assertEquals("", string0);
  }
}
