/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.snapshots;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.awt.geom.Ellipse2D;
import net.virtualinfinity.atrobots.measures.AbsoluteAngle;
import net.virtualinfinity.atrobots.measures.Duration;
import net.virtualinfinity.atrobots.measures.Vector;
import net.virtualinfinity.atrobots.snapshots.ExplosionSnapshot;
import net.virtualinfinity.atrobots.snapshots.SnapshotAdaptor;
import net.virtualinfinity.atrobots.snapshots.SnapshotVisitor;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class ExplosionSnapshotEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Duration duration0 = Duration.fromCycles(31);
      ExplosionSnapshot explosionSnapshot0 = new ExplosionSnapshot((-782.8464297682791), duration0);
      AbsoluteAngle absoluteAngle0 = AbsoluteAngle.fromBygrees(31);
      Vector vector0 = absoluteAngle0.toUnitVector();
      explosionSnapshot0.setPositionVector(vector0);
      Ellipse2D.Double ellipse2D_Double0 = explosionSnapshot0.getExplosionShape();
      assertNotNull(ellipse2D_Double0);
      assertEquals(1627.6928595365582, ellipse2D_Double0.height, 0.01D);
      assertEquals(1627.6928595365582, ellipse2D_Double0.width, 0.01D);
  }

  @Test
  public void test1()  throws Throwable  {
      Duration duration0 = Duration.fromCycles(31);
      ExplosionSnapshot explosionSnapshot0 = new ExplosionSnapshot((-782.8464297682791), duration0);
      SnapshotAdaptor snapshotAdaptor0 = new SnapshotAdaptor();
      explosionSnapshot0.visit((SnapshotVisitor) snapshotAdaptor0);
      assertEquals((-782.8464297682791), explosionSnapshot0.getRadius(), 0.01D);
  }
}
