/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.snapshots;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.snapshots.MineSnapshot;
import net.virtualinfinity.atrobots.snapshots.SnapshotAdaptor;
import net.virtualinfinity.atrobots.snapshots.SnapshotVisitor;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class MineSnapshotEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      MineSnapshot mineSnapshot0 = new MineSnapshot();
      mineSnapshot0.setTriggerRadius((-1728.0539595116393));
      assertEquals((-1728.0539595116393), mineSnapshot0.getTriggerRadius(), 0.01D);
  }

  @Test
  public void test1()  throws Throwable  {
      MineSnapshot mineSnapshot0 = new MineSnapshot();
      SnapshotAdaptor snapshotAdaptor0 = new SnapshotAdaptor();
      mineSnapshot0.visit((SnapshotVisitor) snapshotAdaptor0);
      assertEquals(false, mineSnapshot0.isDead());
  }

  @Test
  public void test2()  throws Throwable  {
      MineSnapshot mineSnapshot0 = new MineSnapshot();
      double double0 = mineSnapshot0.getTriggerRadius();
      assertEquals(0.0, double0, 0.01D);
  }
}
