/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.snapshots;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.measures.Duration;
import net.virtualinfinity.atrobots.snapshots.MissileSnapshot;
import net.virtualinfinity.atrobots.snapshots.SnapshotAdaptor;
import net.virtualinfinity.atrobots.snapshots.SnapshotVisitor;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class MissileSnapshotEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Duration duration0 = Duration.ZERO_CYCLE;
      MissileSnapshot missileSnapshot0 = new MissileSnapshot(false, duration0);
      Duration duration1 = missileSnapshot0.getAge();
      assertNotNull(duration1);
      assertEquals(false, missileSnapshot0.isOverburn());
  }

  @Test
  public void test1()  throws Throwable  {
      Duration duration0 = Duration.ZERO_CYCLE;
      MissileSnapshot missileSnapshot0 = new MissileSnapshot(false, duration0);
      SnapshotAdaptor snapshotAdaptor0 = new SnapshotAdaptor();
      missileSnapshot0.visit((SnapshotVisitor) snapshotAdaptor0);
      assertEquals(false, missileSnapshot0.isOverburn());
  }

  @Test
  public void test2()  throws Throwable  {
      Duration duration0 = Duration.ZERO_CYCLE;
      MissileSnapshot missileSnapshot0 = new MissileSnapshot(false, duration0);
      boolean boolean0 = missileSnapshot0.isOverburn();
      assertEquals(false, boolean0);
  }
}
