/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.snapshots;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.snapshots.SnapshotAdaptor;
import net.virtualinfinity.atrobots.snapshots.SnapshotVisitor;
import net.virtualinfinity.atrobots.snapshots.UnknownSnapshot;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class UnknownSnapshotEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      UnknownSnapshot unknownSnapshot0 = new UnknownSnapshot("1lfbt]f]up");
      SnapshotAdaptor snapshotAdaptor0 = new SnapshotAdaptor();
      unknownSnapshot0.visit((SnapshotVisitor) snapshotAdaptor0);
      assertEquals(false, unknownSnapshot0.isDead());
  }
}
