/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.debugger;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.PipedReader;
import java.io.PipedWriter;
import java.io.Reader;
import net.virtualinfinity.atrobots.debugger.ConsoleImpl;
import net.virtualinfinity.atrobots.debugger.ConsoleInput;
import net.virtualinfinity.atrobots.debugger.ConsoleOutput;
import net.virtualinfinity.atrobots.debugger.ReaderConsoleInput;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class ConsoleImplEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ConsoleImpl consoleImpl0 = new ConsoleImpl((ConsoleInput) null, (ConsoleOutput) null, (ConsoleOutput) null);
      // Undeclared exception!
      try {
        consoleImpl0.readline();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      PipedWriter pipedWriter0 = new PipedWriter();
      PipedReader pipedReader0 = new PipedReader(pipedWriter0, 82);
      BufferedReader bufferedReader0 = new BufferedReader((Reader) pipedReader0, 1);
      ReaderConsoleInput readerConsoleInput0 = new ReaderConsoleInput(bufferedReader0);
      ConsoleImpl consoleImpl0 = new ConsoleImpl((ConsoleInput) readerConsoleInput0, (ConsoleOutput) null, (ConsoleOutput) null);
      // Undeclared exception!
      try {
        consoleImpl0.handleException((Exception) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
