/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.debugger;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import net.virtualinfinity.atrobots.debugger.ReaderConsoleInput;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class ReaderConsoleInputEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      byte[] byteArray0 = new byte[5];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      ReaderConsoleInput readerConsoleInput0 = new ReaderConsoleInput((InputStream) byteArrayInputStream0);
      readerConsoleInput0.readLine();
      assertEquals(-1, byteArrayInputStream0.read());
      assertEquals(0, byteArrayInputStream0.available());
  }
}
