/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.robot;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.robot.FinalRobotScore;
import net.virtualinfinity.atrobots.robot.Robot;
import net.virtualinfinity.atrobots.robot.RobotScore;
import net.virtualinfinity.atrobots.robot.RobotScoreKeeper;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class FinalRobotScoreEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      FinalRobotScore finalRobotScore0 = (FinalRobotScore)FinalRobotScore.copyOf((RobotScore) robotScoreKeeper0);
      assertNotNull(finalRobotScore0);
      
      Robot robot0 = new Robot("}i|#uXrhd;hB1C*j%A=", (-10), (RobotScore) finalRobotScore0);
      int int0 = robot0.getTotalDeaths();
      assertEquals(0, int0);
  }

  @Test
  public void test1()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      FinalRobotScore finalRobotScore0 = (FinalRobotScore)FinalRobotScore.copyOf((RobotScore) robotScoreKeeper0);
      assertNotNull(finalRobotScore0);
      
      Robot robot0 = new Robot("}i|#uXrhd;hB1C*j%A=", (-10), (RobotScore) finalRobotScore0);
      int int0 = robot0.getTotalTies();
      assertEquals(0, int0);
  }

  @Test
  public void test2()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      FinalRobotScore finalRobotScore0 = (FinalRobotScore)FinalRobotScore.copyOf((RobotScore) robotScoreKeeper0);
      assertNotNull(finalRobotScore0);
      
      Robot robot0 = new Robot("}i|#uXrhd;hB1C*j%A=", (-10), (RobotScore) finalRobotScore0);
      int int0 = robot0.getTotalWins();
      assertEquals(0, int0);
  }

  @Test
  public void test3()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      FinalRobotScore finalRobotScore0 = (FinalRobotScore)FinalRobotScore.copyOf((RobotScore) robotScoreKeeper0);
      assertNotNull(finalRobotScore0);
      
      Robot robot0 = new Robot("}i|#uXrhd;hB1C*j%A=", (-10), (RobotScore) finalRobotScore0);
      int int0 = robot0.getTotalKills();
      assertEquals(0, int0);
  }

  @Test
  public void test4()  throws Throwable  {
      // Undeclared exception!
      try {
        FinalRobotScore.copyOf((RobotScore) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test5()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      FinalRobotScore finalRobotScore0 = (FinalRobotScore)FinalRobotScore.copyOf((RobotScore) robotScoreKeeper0);
      FinalRobotScore finalRobotScore1 = (FinalRobotScore)FinalRobotScore.copyOf((RobotScore) finalRobotScore0);
      assertEquals(0, finalRobotScore1.getTotalTies());
  }
}
