/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.robot;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.arena.Heading;
import net.virtualinfinity.atrobots.arena.Position;
import net.virtualinfinity.atrobots.hardware.turret.Turret;
import net.virtualinfinity.atrobots.measures.AbsoluteAngle;
import net.virtualinfinity.atrobots.measures.AngleBracket;
import net.virtualinfinity.atrobots.measures.RelativeAngle;
import net.virtualinfinity.atrobots.robot.Robot;
import net.virtualinfinity.atrobots.robot.RobotScanner;
import net.virtualinfinity.atrobots.robot.RobotScore;
import net.virtualinfinity.atrobots.robot.RobotScoreKeeper;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class RobotScannerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      AngleBracket angleBracket0 = AngleBracket.all();
      RobotScanner robotScanner0 = new RobotScanner((Robot) null, (Position) null, angleBracket0, (double) (-6), false);
      robotScanner0.visit((Robot) null);
  }

  @Test
  public void test1()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("`^r)8Dr|b6z_vl!", 0, (RobotScore) robotScoreKeeper0);
      Position position0 = new Position();
      Turret turret0 = new Turret();
      Heading heading0 = turret0.getHeading();
      AbsoluteAngle absoluteAngle0 = heading0.getAngle();
      RelativeAngle relativeAngle0 = RelativeAngle.fromRadians((double) 0);
      AngleBracket angleBracket0 = AngleBracket.around(absoluteAngle0, relativeAngle0);
      RobotScanner robotScanner0 = new RobotScanner(robot0, position0, angleBracket0, (double) 0, false);
      Robot robot1 = new Robot("`^r)8Dr|b6z_vl!", 0, (RobotScore) robotScoreKeeper0);
      // Undeclared exception!
      try {
        robotScanner0.visit(robot1);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test2()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("`^r)8Dr|b6z_vl!", 0, (RobotScore) robotScoreKeeper0);
      Position position0 = new Position();
      Turret turret0 = new Turret();
      Heading heading0 = turret0.getHeading();
      AbsoluteAngle absoluteAngle0 = heading0.getAngle();
      RelativeAngle relativeAngle0 = RelativeAngle.fromRadians((double) 0);
      AngleBracket angleBracket0 = AngleBracket.around(absoluteAngle0, relativeAngle0);
      RobotScanner robotScanner0 = new RobotScanner(robot0, position0, angleBracket0, (double) 0, false);
      robotScanner0.toScanResult();
      assertEquals("4.73693267299086r/1", heading0.toString());
      assertEquals(4.73693267299086, absoluteAngle0.getNormalizedRadians(), 0.01D);
  }
}
