/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.robot;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.robot.Robot;
import net.virtualinfinity.atrobots.robot.RobotScore;
import net.virtualinfinity.atrobots.robot.RobotScoreKeeper;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class RobotScoreKeeperEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      int int0 = robotScoreKeeper0.getTotalTies();
      assertEquals(0, int0);
  }

  @Test
  public void test1()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      double double0 = robotScoreKeeper0.getTotalDamageInflicted();
      assertEquals(0.0, double0, 0.01D);
  }

  @Test
  public void test2()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      int int0 = robotScoreKeeper0.getTotalWins();
      assertEquals(0, int0);
  }

  @Test
  public void test3()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("72Fu#TmU!h7xF7/G(Et", 0, (RobotScore) robotScoreKeeper0);
      robotScoreKeeper0.killedRobot(robot0);
      assertEquals(1, robotScoreKeeper0.totalKills);
      assertEquals(1, robot0.getTotalKills());
  }

  @Test
  public void test4()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      String string0 = robotScoreKeeper0.toString();
      assertNotNull(string0);
      assertEquals("RobotScoreKeeper{totalTies=0, totalWins=0, totalKills=0, totalDeaths=0, totalDamageInflicted=0.0}", string0);
  }

  @Test
  public void test5()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("", 0, (RobotScore) robotScoreKeeper0);
      robotScoreKeeper0.tiedRound(robot0);
      assertEquals(1, robotScoreKeeper0.totalTies);
      assertEquals(1, robotScoreKeeper0.getTotalTies());
  }

  @Test
  public void test6()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("72Fu#TmU!h7xF7/G(Et", 0, (RobotScore) robotScoreKeeper0);
      robotScoreKeeper0.wonRound(robot0);
      assertEquals(1, robotScoreKeeper0.totalWins);
      assertEquals(1, robotScoreKeeper0.getTotalWins());
  }

  @Test
  public void test7()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("RobotScoreKeeper{totalTies=0, totalWins=0, totalKills=0, totalDeaths=0, totalDamageInflicted=0.0}", 0, (RobotScore) robotScoreKeeper0);
      robotScoreKeeper0.died(robot0);
      assertEquals(1, robotScoreKeeper0.totalDeaths);
      assertEquals(1, robot0.getTotalDeaths());
  }

  @Test
  public void test8()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("72Fu#TmU!h7xF7/G(Et", 0, (RobotScore) robotScoreKeeper0);
      robotScoreKeeper0.inflictedDamage(robot0, 1858.9823291716868);
      assertEquals(1858.9823291716868, robotScoreKeeper0.totalDamageInflicted, 0.01D);
      assertEquals("RobotScoreKeeper{totalTies=0, totalWins=0, totalKills=0, totalDeaths=0, totalDamageInflicted=1858.9823291716868}", robotScoreKeeper0.toString());
  }

  @Test
  public void test9()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      int int0 = robotScoreKeeper0.getTotalKills();
      assertEquals(0, int0);
  }

  @Test
  public void test10()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      int int0 = robotScoreKeeper0.getTotalDeaths();
      assertEquals(0, int0);
  }
}
