/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.robot;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.ArenaObjectVisitor;
import net.virtualinfinity.atrobots.ArenaObjectVisitorAdaptor;
import net.virtualinfinity.atrobots.arena.Arena;
import net.virtualinfinity.atrobots.arena.Explosion;
import net.virtualinfinity.atrobots.arena.FrameBuilder;
import net.virtualinfinity.atrobots.arena.Heading;
import net.virtualinfinity.atrobots.arena.Odometer;
import net.virtualinfinity.atrobots.arena.Position;
import net.virtualinfinity.atrobots.arena.Speed;
import net.virtualinfinity.atrobots.arenaobjects.DamageInflicter;
import net.virtualinfinity.atrobots.computer.Computer;
import net.virtualinfinity.atrobots.computer.HardwareBus;
import net.virtualinfinity.atrobots.computer.Memory;
import net.virtualinfinity.atrobots.computer.MemoryCell;
import net.virtualinfinity.atrobots.hardware.armor.Armor;
import net.virtualinfinity.atrobots.hardware.mines.MineLayer;
import net.virtualinfinity.atrobots.hardware.radio.Transceiver;
import net.virtualinfinity.atrobots.hardware.scanning.radar.Radar;
import net.virtualinfinity.atrobots.hardware.scanning.sonar.Sonar;
import net.virtualinfinity.atrobots.hardware.shield.Shield;
import net.virtualinfinity.atrobots.hardware.throttle.Throttle;
import net.virtualinfinity.atrobots.hardware.transponder.Transponder;
import net.virtualinfinity.atrobots.hardware.turret.Turret;
import net.virtualinfinity.atrobots.measures.AbsoluteAngle;
import net.virtualinfinity.atrobots.measures.Duration;
import net.virtualinfinity.atrobots.measures.Vector;
import net.virtualinfinity.atrobots.robot.Robot;
import net.virtualinfinity.atrobots.robot.RobotListener;
import net.virtualinfinity.atrobots.robot.RobotScore;
import net.virtualinfinity.atrobots.robot.RobotScoreKeeper;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class RobotEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("", (-1431), (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      ArenaObjectVisitorAdaptor arenaObjectVisitorAdaptor0 = new ArenaObjectVisitorAdaptor();
      robot0.accept((ArenaObjectVisitor) arenaObjectVisitorAdaptor0);
      assertEquals(-1431, robot0.getId());
      assertEquals(0, robot0.getRoundKills());
  }

  @Test
  public void test1()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("'3mY(|NXhnE\"\"??", (-16), (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      // Undeclared exception!
      try {
        robot0.destruct();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test2()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("OuZ$tOfBounds: @", (-1946), (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      Memory memory0 = new Memory();
      MemoryCell memoryCell0 = memory0.getCell((-1946));
      Robot.GetRobotStatisticsInterrupt robot_GetRobotStatisticsInterrupt0 = robot0.createGetRobotStatisticsInterrupt(memoryCell0, memoryCell0, memoryCell0);
      // Undeclared exception!
      try {
        robot_GetRobotStatisticsInterrupt0.handleInterrupt();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test3()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("JEQ", (-17), (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      robot0.getSonar();
      assertEquals(0, robot0.getRoundKills());
      assertEquals(-17, robot0.getId());
  }

  @Test
  public void test4()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("Kills(rEund/toal): ", 119, (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      // Undeclared exception!
      try {
        robot0.getSnapshot();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test5()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("3", 1714, (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      robot0.reset();
      assertEquals(0, robot0.getRoundKills());
      assertEquals(1714, robot0.getId());
      assertEquals(false, robot0.isOverburn());
  }

  @Test
  public void test6()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("1W+=){Zz6]O", (-1347), (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      // Undeclared exception!
      try {
        robot0.setComputer((Computer) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test7()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("3", 1714, (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      robot0.setTransceiver((Transceiver) null);
      assertEquals(1714, robot0.getId());
      assertEquals(0, robot0.getRoundKills());
  }

  @Test
  public void test8()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("K^", 226, (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      // Undeclared exception!
      try {
        robot0.getTurretShift();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test9()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("OuZ$tOfBounds: @", (-1946), (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      Throttle throttle0 = new Throttle((double) (-1946));
      robot0.setThrottle(throttle0);
      assertEquals(0, robot0.getRoundKills());
      assertEquals(-1946, robot0.getId());
  }

  @Test
  public void test10()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("2:_2:jjv;uqT.6", 64, (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      robot0.getThrottle();
      assertEquals(64, robot0.getId());
      assertEquals(0, robot0.getRoundKills());
  }

  @Test
  public void test11()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("K^", 226, (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      robot0.setMineLayer((MineLayer) null);
      assertEquals(0, robot0.getRoundKills());
      assertEquals(226, robot0.getId());
  }

  @Test
  public void test12()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("aI-/puRa`>v/", (-1), (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      Duration duration0 = robot0.getLastDamageTaken();
      assertNotNull(duration0);
      assertEquals("0s", duration0.toString());
      assertEquals(-1, robot0.getId());
      assertEquals(0, robot0.getRoundKills());
  }

  @Test
  public void test13()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("OuZ$tOfBounds: @", (-1946), (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      Speed speed0 = robot0.getSpeed();
      assertEquals(-1946, robot0.getId());
      assertNotNull(speed0);
      assertEquals(0, robot0.getRoundKills());
  }

  @Test
  public void test14()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("K^", 226, (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      Heading heading0 = robot0.getHeading();
      assertNotNull(heading0);
      assertEquals("4.000621894805752r/227", heading0.toString());
  }

  @Test
  public void test15()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("1W+=){Zz6]O", (-1347), (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      HardwareBus hardwareBus0 = new HardwareBus();
      robot0.setHardwareBus(hardwareBus0);
      assertEquals(0, robot0.getRoundKills());
      assertEquals(-1347, robot0.getId());
  }

  @Test
  public void test16()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("", (-1431), (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      Duration duration0 = robot0.getLastDamageGiven();
      assertEquals(-1431, robot0.getId());
      assertEquals("0s", duration0.toString());
      assertNotNull(duration0);
      assertEquals(0, robot0.getRoundKills());
  }

  @Test
  public void test17()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("OuZ$tOfBounds: @", (-1946), (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      robot0.getOverburnLatchPort();
      assertEquals(0, robot0.getRoundKills());
      assertEquals(-1946, robot0.getId());
  }

  @Test
  public void test18()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("2:_2:jjv;uqT.6", 64, (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      Sonar sonar0 = new Sonar();
      robot0.setSonar(sonar0);
      assertEquals(0, robot0.getRoundKills());
      assertEquals(64, robot0.getId());
  }

  @Test
  public void test19()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("JEQ", (-17), (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      FrameBuilder frameBuilder0 = new FrameBuilder();
      Arena arena0 = new Arena(frameBuilder0);
      // Undeclared exception!
      try {
        robot0.setArena(arena0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test20()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("2:_2:jjv;uqT.6", 64, (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      robot0.setTransponder((Transponder) null);
      assertEquals(64, robot0.getId());
      assertEquals(0, robot0.getRoundKills());
  }

  @Test
  public void test21()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("2:_2:jjv;uqT.6", 64, (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      Heading heading0 = robot0.getDesiredHeading();
      assertNotNull(heading0);
      assertEquals("5.841398840268521r/46", heading0.toString());
  }

  @Test
  public void test22()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("Not addressable$erroV.", 2, (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      robot0.getRadar();
      assertEquals(0, robot0.getRoundKills());
      assertEquals(2, robot0.getId());
  }

  @Test
  public void test23()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("thRS%\":98H`L>fp2", (-14), (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      robot0.getHardwareBus();
      assertEquals(0, robot0.getRoundKills());
      assertEquals(-14, robot0.getId());
  }

  @Test
  public void test24()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("$u", 7, (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      robot0.getTotalDeaths();
      assertEquals(0, robot0.getRoundKills());
      assertEquals(7, robot0.getId());
  }

  @Test
  public void test25()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("$u", 7, (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      robot0.getTotalTies();
      assertEquals(0, robot0.getRoundKills());
      assertEquals(7, robot0.getId());
  }

  @Test
  public void test26()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("Not addressable$erroV.", 2, (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      robot0.getShutdownLevelLatchPort();
      assertEquals(2, robot0.getId());
      assertEquals(0, robot0.getRoundKills());
  }

  @Test
  public void test27()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("3", 1714, (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      robot0.getTransceiver();
      assertEquals(1714, robot0.getId());
      assertEquals(0, robot0.getRoundKills());
  }

  @Test
  public void test28()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("", (-1431), (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      String string0 = robot0.getName();
      assertNotNull(string0);
      assertEquals(-1431, robot0.getId());
      assertEquals(0, robot0.getRoundKills());
  }

  @Test
  public void test29()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("", (-1431), (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      Odometer odometer0 = robot0.getOdometer();
      assertEquals(0, robot0.getRoundKills());
      assertNotNull(odometer0);
      assertEquals(-1431, robot0.getId());
  }

  @Test
  public void test30()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("aI-/puRa`>v/", (-1), (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      robot0.getTurretOffsetSensor();
      assertEquals(0, robot0.getRoundKills());
      assertEquals(-1, robot0.getId());
  }

  @Test
  public void test31()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("2:_2:jjv;uqT.6", 64, (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      robot0.setTurret((Turret) null);
      assertEquals(64, robot0.getId());
      assertEquals(0, robot0.getRoundKills());
  }

  @Test
  public void test32()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("Not addressable$erroV.", 2, (RobotScore) robotScoreKeeper0);
      robot0.addRobotListener((RobotListener) robotScoreKeeper0);
      robot0.tieRound();
      assertEquals(1, robotScoreKeeper0.getTotalTies());
      assertEquals(2, robot0.getId());
  }

  @Test
  public void test33()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("$u", 7, (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      robot0.getAimTurretPort();
      assertEquals(0, robot0.getRoundKills());
      assertEquals(7, robot0.getId());
  }

  @Test
  public void test34()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("K^", 226, (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      robot0.getMineLayer();
      assertEquals(0, robot0.getRoundKills());
      assertEquals(226, robot0.getId());
  }

  @Test
  public void test35()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("JEQ", (-17), (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      robot0.getShield();
      assertEquals(-17, robot0.getId());
      assertEquals(0, robot0.getRoundKills());
  }

  @Test
  public void test36()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("aI-/puRa`>v/", (-1), (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      AbsoluteAngle absoluteAngle0 = AbsoluteAngle.fromCartesian((double) (-1), (double) (-1));
      Explosion explosion0 = new Explosion((Vector) null, (double) (-1));
      Position position0 = explosion0.getPosition();
      robot0.createMissile(absoluteAngle0, position0, (double) (-1));
      assertEquals(-1, robot0.getId());
      assertEquals(0, robot0.getRoundKills());
  }

  @Test
  public void test37()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("1W+=){Zz6]O", (-1347), (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      robot0.getComputer();
      assertEquals(0, robot0.getRoundKills());
      assertEquals(-1347, robot0.getId());
  }

  @Test
  public void test38()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("2:_2:jjv;uqT.6", 64, (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      robot0.getTransponder();
      assertEquals(0, robot0.getRoundKills());
      assertEquals(64, robot0.getId());
  }

  @Test
  public void test39()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("Not addressable$erroV.", 2, (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      robot0.setRadar((Radar) null);
      assertEquals(0, robot0.getRoundKills());
      assertEquals(2, robot0.getId());
  }

  @Test
  public void test40()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("2:_2:jjv;uqT.6", 64, (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      Memory memory0 = new Memory();
      MemoryCell memoryCell0 = memory0.getCell(64);
      robot0.createGetRobotInfoInterruptHandler(memoryCell0, memoryCell0, memoryCell0);
      assertEquals(0, robot0.getRoundKills());
      assertEquals(64, robot0.getId());
  }

  @Test
  public void test41()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("$u", 7, (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      robot0.getTotalWins();
      assertEquals(7, robot0.getId());
      assertEquals(0, robot0.getRoundKills());
  }

  @Test
  public void test42()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("$u", 7, (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      int int0 = robot0.getRoundKills();
      assertEquals(7, robot0.getId());
      assertEquals(0, int0);
  }

  @Test
  public void test43()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("", (-17), (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      // Undeclared exception!
      try {
        robot0.collides();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test44()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("?", 0, (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      Shield shield0 = new Shield((double) 0);
      robot0.setShield(shield0);
      Armor armor0 = new Armor(38.554081360616756);
      robot0.setArmor(armor0);
      robot0.inflictDamage((DamageInflicter) robot0, 0.0);
      assertEquals(0, robot0.getId());
      assertEquals(0, robot0.getRoundKills());
  }

  @Test
  public void test45()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("XB", (-1180), (RobotScore) robotScoreKeeper0);
      robot0.addRobotListener((RobotListener) robotScoreKeeper0);
      // Undeclared exception!
      try {
        robot0.armorDepleted();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test46()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("XB", (-1180), (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      robot0.setOverburn(true);
      // Undeclared exception!
      try {
        robot0.armorDepleted();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test47()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("n\b~]8F\"eq!W", (-1), (RobotScore) robotScoreKeeper0);
      robot0.addRobotListener((RobotListener) robotScoreKeeper0);
      robot0.winRound();
      assertEquals(1, robotScoreKeeper0.getTotalWins());
      assertEquals(0, robot0.getRoundKills());
  }

  @Test
  public void test48()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("Not addressable$erroV.", 2, (RobotScore) robotScoreKeeper0);
      assertNotNull(robot0);
      
      robot0.tieRound();
      assertEquals(2, robot0.getId());
      assertEquals(0, robot0.getRoundKills());
  }

  @Test
  public void test49()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("n\b~]8F\"eq!W", (-1), (RobotScore) robotScoreKeeper0);
      robot0.addRobotListener((RobotListener) robotScoreKeeper0);
      robot0.killedRobot();
      assertEquals(1, robotScoreKeeper0.getTotalKills());
      assertEquals("RobotScoreKeeper{totalTies=0, totalWins=0, totalKills=1, totalDeaths=0, totalDamageInflicted=0.0}", robotScoreKeeper0.toString());
  }
}
