/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.compiler;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.arena.Heading;
import net.virtualinfinity.atrobots.compiler.AtRobotPortFactory;
import net.virtualinfinity.atrobots.hardware.throttle.Throttle;
import net.virtualinfinity.atrobots.ports.PortHandler;
import net.virtualinfinity.atrobots.robot.Robot;
import net.virtualinfinity.atrobots.robot.RobotScore;
import net.virtualinfinity.atrobots.robot.RobotScoreKeeper;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class AtRobotPortFactoryEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Heading heading0 = new Heading();
      PortHandler portHandler0 = AtRobotPortFactory.getRotationPort(heading0);
      assertNotNull(portHandler0);
  }

  @Test
  public void test1()  throws Throwable  {
      AtRobotPortFactory atRobotPortFactory0 = new AtRobotPortFactory();
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot((String) null, 1390, (RobotScore) robotScoreKeeper0);
      Throttle throttle0 = new Throttle((double) 1390);
      robot0.setThrottle(throttle0);
      // Undeclared exception!
      try {
        atRobotPortFactory0.createPortHandlers(robot0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
