/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.compiler;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.Map;
import net.virtualinfinity.atrobots.compiler.HardwareSpecification;
import net.virtualinfinity.atrobots.compiler.RobotConfigurer;
import net.virtualinfinity.atrobots.hardware.radio.Transceiver;
import net.virtualinfinity.atrobots.hardware.scanning.radar.Radar;
import net.virtualinfinity.atrobots.hardware.scanning.sonar.Sonar;
import net.virtualinfinity.atrobots.hardware.transponder.Transponder;
import net.virtualinfinity.atrobots.hardware.turret.Turret;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class HardwareSpecificationEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Hashtable<String, Integer> hashtable0 = new Hashtable<String, Integer>();
      HardwareSpecification hardwareSpecification0 = new HardwareSpecification((Map<String, Integer>) hashtable0);
      RobotConfigurer robotConfigurer0 = new RobotConfigurer();
      // Undeclared exception!
      try {
        hardwareSpecification0.buildRobotConfigurer(robotConfigurer0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      Hashtable<String, Integer> hashtable0 = new Hashtable<String, Integer>();
      HardwareSpecification hardwareSpecification0 = new HardwareSpecification((Map<String, Integer>) hashtable0);
      Turret turret0 = hardwareSpecification0.createTurret();
      assertNotNull(turret0);
  }

  @Test
  public void test2()  throws Throwable  {
      HardwareSpecification hardwareSpecification0 = new HardwareSpecification((Map<String, Integer>) null);
      // Undeclared exception!
      try {
        hardwareSpecification0.createShield();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test3()  throws Throwable  {
      HardwareSpecification hardwareSpecification0 = new HardwareSpecification((Map<String, Integer>) null);
      Transponder transponder0 = hardwareSpecification0.createTransponder();
      assertEquals(0, transponder0.getId());
  }

  @Test
  public void test4()  throws Throwable  {
      Hashtable<String, Integer> hashtable0 = new Hashtable<String, Integer>();
      HardwareSpecification hardwareSpecification0 = new HardwareSpecification((Map<String, Integer>) hashtable0);
      Radar radar0 = hardwareSpecification0.createRadar();
      assertNotNull(radar0);
  }

  @Test
  public void test5()  throws Throwable  {
      HardwareSpecification hardwareSpecification0 = new HardwareSpecification((Map<String, Integer>) null);
      Sonar sonar0 = hardwareSpecification0.createSonar();
      assertNotNull(sonar0);
  }

  @Test
  public void test6()  throws Throwable  {
      HashMap<String, Integer> hashMap0 = new HashMap<String, Integer>();
      HardwareSpecification hardwareSpecification0 = new HardwareSpecification((Map<String, Integer>) hashMap0);
      // Undeclared exception!
      try {
        hardwareSpecification0.createMineLayer();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test7()  throws Throwable  {
      Hashtable<String, Integer> hashtable0 = new Hashtable<String, Integer>();
      HardwareSpecification hardwareSpecification0 = new HardwareSpecification((Map<String, Integer>) hashtable0);
      Transceiver transceiver0 = hardwareSpecification0.createTransceiver();
      assertEquals(0, transceiver0.getChannel());
  }

  @Test
  public void test8()  throws Throwable  {
      HardwareSpecification hardwareSpecification0 = new HardwareSpecification((Map<String, Integer>) null);
      // Undeclared exception!
      try {
        hardwareSpecification0.createArmor();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
