/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.interrupts;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.computer.MemoryCell;
import net.virtualinfinity.atrobots.interrupts.CopyMemoryCellsInterrupt;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class CopyMemoryCellsInterruptEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      MemoryCell[] memoryCellArray0 = new MemoryCell[1];
      CopyMemoryCellsInterrupt copyMemoryCellsInterrupt0 = new CopyMemoryCellsInterrupt(memoryCellArray0);
      // Undeclared exception!
      try {
        copyMemoryCellsInterrupt0.handleInterrupt();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      } catch(ArrayIndexOutOfBoundsException e) {
        /*
         * 1
         */
      }
  }
}
