/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.interrupts;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.computer.AtRobotsCommunicationsQueue;
import net.virtualinfinity.atrobots.computer.Memory;
import net.virtualinfinity.atrobots.computer.MemoryCell;
import net.virtualinfinity.atrobots.computer.MemoryRegion;
import net.virtualinfinity.atrobots.interrupts.GetQueueSizeInterrupt;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class GetQueueSizeInterruptEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Memory memory0 = new Memory();
      MemoryRegion memoryRegion0 = new MemoryRegion(memory0, 372, 372);
      MemoryCell memoryCell0 = new MemoryCell(memory0, 372);
      AtRobotsCommunicationsQueue atRobotsCommunicationsQueue0 = new AtRobotsCommunicationsQueue(memoryRegion0, memoryCell0, memoryCell0);
      GetQueueSizeInterrupt getQueueSizeInterrupt0 = new GetQueueSizeInterrupt(atRobotsCommunicationsQueue0, memoryCell0);
      // Undeclared exception!
      try {
        getQueueSizeInterrupt0.handleInterrupt();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
