/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.interrupts;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.computer.Memory;
import net.virtualinfinity.atrobots.computer.MemoryArray;
import net.virtualinfinity.atrobots.computer.MemoryCell;
import net.virtualinfinity.atrobots.computer.ReadOnlyMemoryArray;
import net.virtualinfinity.atrobots.hardware.HasOverburner;
import net.virtualinfinity.atrobots.interrupts.OverburnInterrupt;
import net.virtualinfinity.atrobots.robot.Robot;
import net.virtualinfinity.atrobots.robot.RobotScore;
import net.virtualinfinity.atrobots.robot.RobotScoreKeeper;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class OverburnInterruptEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Memory memory0 = new Memory();
      ReadOnlyMemoryArray readOnlyMemoryArray0 = new ReadOnlyMemoryArray(2);
      memory0.addMemoryArray((MemoryArray) readOnlyMemoryArray0);
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("1E\no_f+m.5F", 2, (RobotScore) robotScoreKeeper0);
      MemoryCell memoryCell0 = memory0.getCell(0);
      OverburnInterrupt overburnInterrupt0 = new OverburnInterrupt((HasOverburner) robot0, memoryCell0);
      overburnInterrupt0.handleInterrupt();
      assertEquals(false, robot0.isOverburn());
  }

  @Test
  public void test1()  throws Throwable  {
      Memory memory0 = new Memory();
      ReadOnlyMemoryArray readOnlyMemoryArray0 = new ReadOnlyMemoryArray(2);
      memory0.addMemoryArray((MemoryArray) readOnlyMemoryArray0);
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("1E\no_f+m.5F", 2, (RobotScore) robotScoreKeeper0);
      MemoryCell memoryCell0 = memory0.getCell(0);
      OverburnInterrupt overburnInterrupt0 = new OverburnInterrupt((HasOverburner) robot0, memoryCell0);
      short[] shortArray0 = new short[5];
      shortArray0[0] = (short)1;
      readOnlyMemoryArray0.flash(shortArray0);
      overburnInterrupt0.handleInterrupt();
      assertEquals(true, robot0.isOverburn());
  }
}
