/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.interrupts;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.computer.Memory;
import net.virtualinfinity.atrobots.computer.MemoryArray;
import net.virtualinfinity.atrobots.computer.MemoryCell;
import net.virtualinfinity.atrobots.computer.ReadOnlyMemoryArray;
import net.virtualinfinity.atrobots.hardware.turret.Turret;
import net.virtualinfinity.atrobots.interrupts.SetKeepshiftInterrupt;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class SetKeepshiftInterruptEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Memory memory0 = new Memory();
      ReadOnlyMemoryArray readOnlyMemoryArray0 = new ReadOnlyMemoryArray(44);
      memory0.addMemoryArray((MemoryArray) readOnlyMemoryArray0);
      MemoryCell memoryCell0 = memory0.getCell(18);
      SetKeepshiftInterrupt setKeepshiftInterrupt0 = new SetKeepshiftInterrupt((Turret) null, memoryCell0);
      // Undeclared exception!
      try {
        setKeepshiftInterrupt0.handleInterrupt();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
