/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.interrupts;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.computer.MemoryCell;
import net.virtualinfinity.atrobots.hardware.radio.Transceiver;
import net.virtualinfinity.atrobots.interrupts.TransmitInterrupt;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TransmitInterruptEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      TransmitInterrupt transmitInterrupt0 = new TransmitInterrupt((Transceiver) null, (MemoryCell) null);
      // Undeclared exception!
      try {
        transmitInterrupt0.handleInterrupt();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
