/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.interrupts;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.computer.MemoryCell;
import net.virtualinfinity.atrobots.interrupts.ZeroMemoryCellsInterrupt;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class ZeroMemoryCellsInterruptEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      MemoryCell[] memoryCellArray0 = new MemoryCell[1];
      ZeroMemoryCellsInterrupt zeroMemoryCellsInterrupt0 = new ZeroMemoryCellsInterrupt(memoryCellArray0);
      // Undeclared exception!
      try {
        zeroMemoryCellsInterrupt0.handleInterrupt();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
