/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.ArenaObjectVisitorAdaptor;
import net.virtualinfinity.atrobots.arena.Explosion;
import net.virtualinfinity.atrobots.arena.Position;
import net.virtualinfinity.atrobots.arena.Scan;
import net.virtualinfinity.atrobots.arenaobjects.DamageInflicter;
import net.virtualinfinity.atrobots.hardware.mines.Mine;
import net.virtualinfinity.atrobots.hardware.missiles.Missile;
import net.virtualinfinity.atrobots.measures.AbsoluteAngle;
import net.virtualinfinity.atrobots.measures.AngleBracket;
import net.virtualinfinity.atrobots.measures.RelativeAngle;
import net.virtualinfinity.atrobots.measures.Vector;
import net.virtualinfinity.atrobots.robot.Robot;
import net.virtualinfinity.atrobots.robot.RobotScore;
import net.virtualinfinity.atrobots.robot.RobotScoreKeeper;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class ArenaObjectVisitorAdaptorEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ArenaObjectVisitorAdaptor arenaObjectVisitorAdaptor0 = new ArenaObjectVisitorAdaptor();
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot((String) null, 103, (RobotScore) robotScoreKeeper0);
      Position position0 = robot0.getPosition();
      Missile missile0 = new Missile((DamageInflicter) robot0, position0, (AbsoluteAngle) null, (double) 103, false);
      arenaObjectVisitorAdaptor0.visit(missile0);
  }

  @Test
  public void test1()  throws Throwable  {
      ArenaObjectVisitorAdaptor arenaObjectVisitorAdaptor0 = new ArenaObjectVisitorAdaptor();
      Mine mine0 = new Mine((DamageInflicter) null);
      arenaObjectVisitorAdaptor0.visit(mine0);
  }

  @Test
  public void test2()  throws Throwable  {
      ArenaObjectVisitorAdaptor arenaObjectVisitorAdaptor0 = new ArenaObjectVisitorAdaptor();
      Explosion explosion0 = new Explosion((Vector) null, 6.283185307179586);
      arenaObjectVisitorAdaptor0.visit(explosion0);
  }

  @Test
  public void test3()  throws Throwable  {
      ArenaObjectVisitorAdaptor arenaObjectVisitorAdaptor0 = new ArenaObjectVisitorAdaptor();
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("", 0, (RobotScore) robotScoreKeeper0);
      arenaObjectVisitorAdaptor0.visit(robot0);
  }

  @Test
  public void test4()  throws Throwable  {
      ArenaObjectVisitorAdaptor arenaObjectVisitorAdaptor0 = new ArenaObjectVisitorAdaptor();
      AbsoluteAngle absoluteAngle0 = AbsoluteAngle.fromRadians(0.0);
      RelativeAngle relativeAngle0 = RelativeAngle.fromRadians((-1403.7341131945352));
      AngleBracket angleBracket0 = AngleBracket.clockwiseFrom(absoluteAngle0, relativeAngle0);
      Scan scan0 = new Scan(angleBracket0, 415.1429537229786, true, (Vector) null, true, 1382);
      arenaObjectVisitorAdaptor0.visit(scan0);
  }
}
