/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.hardware.mines;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.arena.Arena;
import net.virtualinfinity.atrobots.arena.Position;
import net.virtualinfinity.atrobots.arenaobjects.DamageInflicter;
import net.virtualinfinity.atrobots.hardware.mines.MineLayer;
import net.virtualinfinity.atrobots.ports.PortHandler;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class MineLayerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      MineLayer mineLayer0 = new MineLayer(1756);
      PortHandler portHandler0 = mineLayer0.getMineBayPort();
      assertEquals(1756, portHandler0.read());
  }

  @Test
  public void test1()  throws Throwable  {
      MineLayer mineLayer0 = new MineLayer(1756);
      PortHandler portHandler0 = mineLayer0.getPlacedMinePort();
      assertEquals(0, portHandler0.read());
  }

  @Test
  public void test2()  throws Throwable  {
      MineLayer mineLayer0 = new MineLayer(1756);
      mineLayer0.setOwner((DamageInflicter) null);
  }

  @Test
  public void test3()  throws Throwable  {
      MineLayer mineLayer0 = new MineLayer(1756);
      Arena arena0 = new Arena();
      mineLayer0.setArena(arena0);
      assertEquals(false, arena0.isOnlyOneRobotAlive());
  }

  @Test
  public void test4()  throws Throwable  {
      MineLayer mineLayer0 = new MineLayer(1756);
      mineLayer0.setPosition((Position) null);
  }

  @Test
  public void test5()  throws Throwable  {
      MineLayer mineLayer0 = new MineLayer(1756);
      DamageInflicter damageInflicter0 = mineLayer0.getOwner();
      assertNull(damageInflicter0);
  }
}
