/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.computer;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.computer.BitShiftRightInstruction;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class BitShiftRightInstructionEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      BitShiftRightInstruction bitShiftRightInstruction0 = new BitShiftRightInstruction(1244);
      int int0 = bitShiftRightInstruction0.combine((short)0, (short)0);
      assertEquals(0, int0);
  }
}
