/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.computer;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.computer.CompareInstruction;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class CompareInstructionEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      CompareInstruction compareInstruction0 = new CompareInstruction((-652));
      assertNotNull(compareInstruction0);
  }
}
