/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.computer;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.computer.DebugInfo;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class DebugInfoEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DebugInfo debugInfo0 = new DebugInfo();
      debugInfo0.addVariable(0, "");
      Integer integer0 = debugInfo0.getVariableAddress("");
      assertEquals(0, (int)integer0);
      
      debugInfo0.getLineForInstructionPointer((int) integer0);
      assertEquals(0.0, integer0.doubleValue(), 0.01D);
  }

  @Test
  public void test1()  throws Throwable  {
      DebugInfo debugInfo0 = new DebugInfo();
      debugInfo0.setLineForInstructionPointer(0, "");
  }

  @Test
  public void test2()  throws Throwable  {
      DebugInfo debugInfo0 = new DebugInfo();
      String string0 = debugInfo0.getVariableName(0);
      assertNotNull(string0);
      assertEquals("@0", string0);
  }

  @Test
  public void test3()  throws Throwable  {
      DebugInfo debugInfo0 = new DebugInfo();
      debugInfo0.addVariable(0, "");
      String string0 = debugInfo0.getVariableName(0);
      assertNotNull(string0);
      assertEquals("@0", string0);
  }
}
