/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.computer;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.computer.Computer;
import net.virtualinfinity.atrobots.computer.EmptyDebugListener;
import net.virtualinfinity.atrobots.robot.Robot;
import net.virtualinfinity.atrobots.robot.RobotScore;
import net.virtualinfinity.atrobots.robot.RobotScoreKeeper;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class EmptyDebugListenerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      EmptyDebugListener emptyDebugListener0 = new EmptyDebugListener();
      emptyDebugListener0.beforeInstruction((Computer) null);
  }

  @Test
  public void test1()  throws Throwable  {
      EmptyDebugListener emptyDebugListener0 = new EmptyDebugListener();
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      Robot robot0 = new Robot("", 13, (RobotScore) robotScoreKeeper0);
      Computer computer0 = robot0.getComputer();
      emptyDebugListener0.afterInstruction(computer0);
  }
}
