/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.computer;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.computer.JumpWhenLessOrEqualInstruction;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class JumpWhenLessOrEqualInstructionEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      JumpWhenLessOrEqualInstruction jumpWhenLessOrEqualInstruction0 = new JumpWhenLessOrEqualInstruction(6);
      assertNotNull(jumpWhenLessOrEqualInstruction0);
  }
}
