/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.computer;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.computer.Flags;
import net.virtualinfinity.atrobots.computer.JumpWhenEqualInstruction;
import net.virtualinfinity.atrobots.computer.MemoryCell;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class JumpWhenEqualInstructionEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      JumpWhenEqualInstruction jumpWhenEqualInstruction0 = new JumpWhenEqualInstruction((-1017));
      Flags flags0 = new Flags((MemoryCell) null);
      // Undeclared exception!
      try {
        jumpWhenEqualInstruction0.conditionMet(flags0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
