/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.computer;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.computer.JumpWhenNotEqualInstruction;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class JumpWhenNotEqualInstructionEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      JumpWhenNotEqualInstruction jumpWhenNotEqualInstruction0 = new JumpWhenNotEqualInstruction(0);
      assertNotNull(jumpWhenNotEqualInstruction0);
  }
}
