/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.computer;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.computer.Program;
import net.virtualinfinity.atrobots.computer.ReadOnlyMemoryArray;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class ProgramEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      short[] shortArray0 = new short[2];
      Program program0 = new Program(shortArray0);
      ReadOnlyMemoryArray readOnlyMemoryArray0 = (ReadOnlyMemoryArray)program0.createProgramMemory();
      assertEquals(2, readOnlyMemoryArray0.size());
  }
}
