/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.computer;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.computer.ReadOnlyMemoryArray;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class ReadOnlyMemoryArrayEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ReadOnlyMemoryArray readOnlyMemoryArray0 = new ReadOnlyMemoryArray(1623);
      // Undeclared exception!
      try {
        readOnlyMemoryArray0.decrement(1623);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      ReadOnlyMemoryArray readOnlyMemoryArray0 = new ReadOnlyMemoryArray(0);
      // Undeclared exception!
      try {
        readOnlyMemoryArray0.or(0, (short) (-1));
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test2()  throws Throwable  {
      ReadOnlyMemoryArray readOnlyMemoryArray0 = new ReadOnlyMemoryArray(255);
      // Undeclared exception!
      try {
        readOnlyMemoryArray0.increment(255);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test3()  throws Throwable  {
      ReadOnlyMemoryArray readOnlyMemoryArray0 = new ReadOnlyMemoryArray(1670);
      // Undeclared exception!
      try {
        readOnlyMemoryArray0.and((-1), (short) (-1361));
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test4()  throws Throwable  {
      ReadOnlyMemoryArray readOnlyMemoryArray0 = new ReadOnlyMemoryArray(428);
      // Undeclared exception!
      try {
        readOnlyMemoryArray0.put((int) (short)0, (short)0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test5()  throws Throwable  {
      ReadOnlyMemoryArray readOnlyMemoryArray0 = new ReadOnlyMemoryArray(770);
      // Undeclared exception!
      try {
        readOnlyMemoryArray0.clear();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test6()  throws Throwable  {
      ReadOnlyMemoryArray readOnlyMemoryArray0 = new ReadOnlyMemoryArray(255);
      short[] shortArray0 = new short[6];
      readOnlyMemoryArray0.flash(shortArray0);
      assertEquals(255, readOnlyMemoryArray0.size());
  }
}
