/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.computer;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.computer.Memory;
import net.virtualinfinity.atrobots.computer.MemoryCell;
import net.virtualinfinity.atrobots.computer.StackMemory;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class StackMemoryEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Memory memory0 = new Memory();
      MemoryCell memoryCell0 = memory0.getCell(1);
      StackMemory stackMemory0 = new StackMemory(memoryCell0, 1);
      // Undeclared exception!
      try {
        stackMemory0.push((short)1);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      StackMemory stackMemory0 = new StackMemory((MemoryCell) null, 0);
      stackMemory0.reset();
  }

  @Test
  public void test2()  throws Throwable  {
      StackMemory stackMemory0 = new StackMemory((MemoryCell) null, 0);
      // Undeclared exception!
      try {
        stackMemory0.pop();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
