/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.tournament;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.compiler.RobotFactory;
import net.virtualinfinity.atrobots.tournament.PairTournamentResults;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class PairTournamentResultsEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      PairTournamentResults pairTournamentResults0 = new PairTournamentResults();
      // Undeclared exception!
      try {
        pairTournamentResults0.getScore((RobotFactory) null, (RobotFactory) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
