/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.game;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.util.List;
import java.util.Vector;
import net.virtualinfinity.atrobots.game.GameResult;
import net.virtualinfinity.atrobots.game.RobotGameResult;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class GameResultEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Vector<RobotGameResult> vector0 = new Vector<RobotGameResult>();
      GameResult gameResult0 = new GameResult((List<RobotGameResult>) vector0);
      List<RobotGameResult> list0 = gameResult0.getResults();
      assertNotNull(list0);
      assertEquals("GameResult{results=[]}", gameResult0.toString());
  }

  @Test
  public void test1()  throws Throwable  {
      Vector<RobotGameResult> vector0 = new Vector<RobotGameResult>();
      GameResult gameResult0 = new GameResult((List<RobotGameResult>) vector0);
      String string0 = gameResult0.toString();
      assertEquals("GameResult{results=[]}", string0);
      assertNotNull(string0);
  }
}
