/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.game;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.compiler.RobotFactory;
import net.virtualinfinity.atrobots.game.RobotGameResult;
import net.virtualinfinity.atrobots.robot.RobotScore;
import net.virtualinfinity.atrobots.robot.RobotScoreKeeper;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class RobotGameResultEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      RobotGameResult robotGameResult0 = new RobotGameResult((RobotFactory) null, (RobotScore) robotScoreKeeper0);
      RobotFactory robotFactory0 = robotGameResult0.getEntrant();
      assertNull(robotFactory0);
  }

  @Test
  public void test1()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      RobotGameResult robotGameResult0 = new RobotGameResult((RobotFactory) null, (RobotScore) robotScoreKeeper0);
      // Undeclared exception!
      try {
        robotGameResult0.compareTo((RobotGameResult) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test2()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      RobotGameResult robotGameResult0 = new RobotGameResult((RobotFactory) null, (RobotScore) robotScoreKeeper0);
      RobotScoreKeeper robotScoreKeeper1 = (RobotScoreKeeper)robotGameResult0.getFinalScore();
      assertEquals(0, robotScoreKeeper1.getTotalKills());
  }

  @Test
  public void test3()  throws Throwable  {
      RobotScoreKeeper robotScoreKeeper0 = new RobotScoreKeeper();
      RobotGameResult robotGameResult0 = new RobotGameResult((RobotFactory) null, (RobotScore) robotScoreKeeper0);
      String string0 = robotGameResult0.toString();
      assertEquals("RobotGameResult{entrant=null, finalScore=RobotScoreKeeper{totalTies=0, totalWins=0, totalKills=0, totalDeaths=0, totalDamageInflicted=0.0}}", string0);
      assertNotNull(string0);
  }
}
