/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.game;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.arena.FrameBuilder;
import net.virtualinfinity.atrobots.game.Game;
import net.virtualinfinity.atrobots.game.Round;
import net.virtualinfinity.atrobots.game.RoundListener;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class RoundEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      FrameBuilder frameBuilder0 = new FrameBuilder();
      Round round0 = new Round(frameBuilder0);
      assertNotNull(round0);
      
      Game game0 = new Game(46);
      round0.addRoundListener((RoundListener) game0);
      boolean boolean0 = round0.step();
      assertEquals(true, boolean0);
  }

  @Test
  public void test1()  throws Throwable  {
      FrameBuilder frameBuilder0 = new FrameBuilder();
      Round round0 = new Round(frameBuilder0);
      round0.finalizeRound();
      assertEquals(true, round0.step());
  }

  @Test
  public void test2()  throws Throwable  {
      FrameBuilder frameBuilder0 = new FrameBuilder();
      Round round0 = new Round(frameBuilder0);
      assertNotNull(round0);
      
      round0.step();
      boolean boolean0 = round0.step();
      assertEquals(true, boolean0);
  }
}
