/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.game;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.game.StandardRoundState;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class StandardRoundStateEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      StandardRoundState standardRoundState0 = new StandardRoundState(1731, 0);
      int int0 = standardRoundState0.getTotalRounds();
      assertEquals(0, standardRoundState0.getRoundNumber());
      assertEquals(1731, int0);
  }

  @Test
  public void test1()  throws Throwable  {
      StandardRoundState standardRoundState0 = new StandardRoundState(1731, 0);
      int int0 = standardRoundState0.getRoundNumber();
      assertEquals(0, int0);
      assertEquals(1731, standardRoundState0.getTotalRounds());
  }
}
