/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.measures;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.measures.AbsoluteAngle;
import net.virtualinfinity.atrobots.measures.CartesianVector;
import net.virtualinfinity.atrobots.measures.Vector;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class CartesianVectorEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      AbsoluteAngle absoluteAngle0 = AbsoluteAngle.fromCartesian((-1255.8721599803443), (-1255.8721599803443));
      CartesianVector cartesianVector0 = (CartesianVector)Vector.createCartesian((-1255.8721599803443), (-1255.8721599803443));
      Vector vector0 = absoluteAngle0.projectAngle((Vector) cartesianVector0);
      assertEquals("<3.9269908169872414r/224, 1776.0714412509963>:<-1255.8721599803443, -1255.8721599803443>", cartesianVector0.toString());
      assertEquals((-1255.8721599803448), vector0.getX(), 0.01D);
  }
}
