/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.measures;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.measures.DistanceOverTime;
import net.virtualinfinity.atrobots.measures.Duration;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class DistanceOverTimeEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DistanceOverTime distanceOverTime0 = new DistanceOverTime((-1064.9168352228146), (Duration) null);
      Duration duration0 = Duration.ONE_CYCLE;
      // Undeclared exception!
      try {
        distanceOverTime0.times(duration0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      Duration duration0 = Duration.ONE_CYCLE;
      DistanceOverTime distanceOverTime0 = new DistanceOverTime(0.0, duration0);
      String string0 = distanceOverTime0.toString();
      assertEquals("0.0/1s", string0);
      assertNotNull(string0);
  }
}
