/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.measures;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.measures.Duration;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class DurationEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Duration duration0 = Duration.ZERO_CYCLE;
      Duration duration1 = duration0.plus(duration0);
      assertEquals("2s", duration1.toString());
      assertNotNull(duration1);
  }

  @Test
  public void test1()  throws Throwable  {
      Duration duration0 = Duration.ZERO_CYCLE;
      double double0 = duration0.divided(duration0);
      assertEquals(1.0, double0, 0.01D);
  }

  @Test
  public void test2()  throws Throwable  {
      Duration duration0 = Duration.ZERO_CYCLE;
      String string0 = duration0.toString();
      assertNotNull(string0);
      assertEquals("1s", string0);
  }

  @Test
  public void test3()  throws Throwable  {
      Duration duration0 = Duration.ZERO_CYCLE;
      int int0 = duration0.compareTo(duration0);
      assertEquals(0, int0);
      assertEquals(1, duration0.getCycles());
  }

  @Test
  public void test4()  throws Throwable  {
      Duration duration0 = Duration.ZERO_CYCLE;
      Duration duration1 = duration0.minus(duration0);
      int int0 = duration1.compareTo(duration0);
      assertEquals(0, duration1.getCycles());
      assertEquals((-1), int0);
  }

  @Test
  public void test5()  throws Throwable  {
      Duration duration0 = Duration.fromCycles(1057);
      Duration duration1 = Duration.ZERO_CYCLE;
      int int0 = duration0.compareTo(duration1);
      assertEquals(1, int0);
      assertEquals(1057, duration0.getCycles());
  }
}
