/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.network;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.awt.HeadlessException;
import net.virtualinfinity.atrobots.arena.SimulationFrameBuffer;
import net.virtualinfinity.atrobots.network.Client;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class ClientEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SimulationFrameBuffer simulationFrameBuffer0 = new SimulationFrameBuffer();
      Client client0 = new Client(simulationFrameBuffer0);
      client0.registerCloseListener();
  }

  @Test
  public void test1()  throws Throwable  {
      SimulationFrameBuffer simulationFrameBuffer0 = new SimulationFrameBuffer();
      Client client0 = new Client(simulationFrameBuffer0);
      // Undeclared exception!
      try {
        client0.buildMenuBar();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test2()  throws Throwable  {
      SimulationFrameBuffer simulationFrameBuffer0 = new SimulationFrameBuffer();
      Client client0 = new Client(simulationFrameBuffer0);
      // Undeclared exception!
      try {
        client0.run();
        fail("Expecting exception: HeadlessException");
      } catch(HeadlessException e) {
      }
  }
}
