/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.network;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.io.IOException;
import java.net.ServerSocket;
import net.virtualinfinity.atrobots.arena.SimulationFrameBuffer;
import net.virtualinfinity.atrobots.network.Server;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class ServerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Server server0 = new Server((ServerSocket) null);
      // Undeclared exception!
      try {
        server0.run();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      ServerSocket serverSocket0 = new ServerSocket();
      Server server0 = new Server(serverSocket0);
      SimulationFrameBuffer simulationFrameBuffer0 = server0.getBuffer();
      assertNull(simulationFrameBuffer0);
  }

  @Test
  public void test2()  throws Throwable  {
      ServerSocket serverSocket0 = new ServerSocket();
      Server server0 = new Server(serverSocket0);
      server0.setBuffer((SimulationFrameBuffer) null);
  }
}
