/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.network;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.io.CharArrayWriter;
import java.io.PipedReader;
import java.io.Reader;
import java.io.Writer;
import net.virtualinfinity.atrobots.arena.SimulationFrameBuffer;
import net.virtualinfinity.atrobots.network.SimulationServerWorker;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class SimulationServerWorkerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      PipedReader pipedReader0 = new PipedReader();
      CharArrayWriter charArrayWriter0 = new CharArrayWriter();
      SimulationServerWorker simulationServerWorker0 = new SimulationServerWorker((Reader) pipedReader0, (Writer) charArrayWriter0);
      SimulationFrameBuffer simulationFrameBuffer0 = new SimulationFrameBuffer();
      simulationServerWorker0.frameAvailable(simulationFrameBuffer0);
  }

  @Test
  public void test1()  throws Throwable  {
      PipedReader pipedReader0 = new PipedReader();
      CharArrayWriter charArrayWriter0 = new CharArrayWriter();
      SimulationServerWorker simulationServerWorker0 = new SimulationServerWorker((Reader) pipedReader0, (Writer) charArrayWriter0);
      simulationServerWorker0.run();
  }
}
