/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.network;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.io.BufferedReader;
import java.io.CharArrayWriter;
import java.io.PipedReader;
import java.io.PrintWriter;
import java.io.Reader;
import java.io.Writer;
import net.virtualinfinity.atrobots.network.SimulationClientWorker;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class SimulationClientWorkerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      PipedReader pipedReader0 = new PipedReader();
      BufferedReader bufferedReader0 = new BufferedReader((Reader) pipedReader0);
      CharArrayWriter charArrayWriter0 = new CharArrayWriter();
      PrintWriter printWriter0 = new PrintWriter((Writer) charArrayWriter0);
      SimulationClientWorker simulationClientWorker0 = new SimulationClientWorker(bufferedReader0, (Writer) printWriter0);
      simulationClientWorker0.run();
      assertEquals("waiting\n", charArrayWriter0.toString());
      assertEquals(8, charArrayWriter0.size());
  }
}
