/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.hardware.turret;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.arena.Heading;
import net.virtualinfinity.atrobots.hardware.missiles.MissileLauncher;
import net.virtualinfinity.atrobots.hardware.scanning.scanner.Scanner;
import net.virtualinfinity.atrobots.hardware.turret.Turret;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TurretEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Turret turret0 = new Turret();
      MissileLauncher missileLauncher0 = turret0.getMissileLauncher();
      turret0.setMissileLauncher(missileLauncher0);
  }

  @Test
  public void test1()  throws Throwable  {
      Turret turret0 = new Turret();
      Heading heading0 = turret0.getHeading();
      assertEquals("4.859651136021711r/6", heading0.toString());
  }

  @Test
  public void test2()  throws Throwable  {
      Turret turret0 = new Turret();
      // Undeclared exception!
      try {
        turret0.reset();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test3()  throws Throwable  {
      Turret turret0 = new Turret();
      Scanner scanner0 = turret0.getScanner();
      assertNull(scanner0);
  }

  @Test
  public void test4()  throws Throwable  {
      Turret turret0 = new Turret();
      turret0.setScanner((Scanner) null);
  }
}
