/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.hardware.scanning.scanner;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.arena.Heading;
import net.virtualinfinity.atrobots.hardware.scanning.ScanSource;
import net.virtualinfinity.atrobots.hardware.scanning.scanner.Scanner;
import net.virtualinfinity.atrobots.measures.RelativeAngle;
import net.virtualinfinity.atrobots.ports.PortHandler;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class ScannerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Scanner scanner0 = new Scanner(11.13106742151496);
      PortHandler portHandler0 = scanner0.getScanPort();
      assertNotNull(portHandler0);
  }

  @Test
  public void test1()  throws Throwable  {
      Scanner scanner0 = new Scanner(11.13106742151496);
      PortHandler portHandler0 = scanner0.getAccuracyPort();
      assertNotNull(portHandler0);
  }

  @Test
  public void test2()  throws Throwable  {
      Scanner scanner0 = new Scanner(11.13106742151496);
      PortHandler portHandler0 = scanner0.getScanArcLatchPort();
      assertEquals(8, portHandler0.read());
  }

  @Test
  public void test3()  throws Throwable  {
      Scanner scanner0 = new Scanner(11.13106742151496);
      Heading heading0 = new Heading();
      scanner0.setHeading(heading0);
      assertEquals("5.325981295538946r/25", heading0.toString());
  }

  @Test
  public void test4()  throws Throwable  {
      Scanner scanner0 = new Scanner(11.13106742151496);
      scanner0.reset();
      assertEquals(0, scanner0.getAccuracy());
  }

  @Test
  public void test5()  throws Throwable  {
      Scanner scanner0 = new Scanner(11.13106742151496);
      int int0 = scanner0.getAccuracy();
      assertEquals(0, int0);
  }

  @Test
  public void test6()  throws Throwable  {
      Scanner scanner0 = new Scanner(11.13106742151496);
      scanner0.setScanSource((ScanSource) null);
      assertEquals(0, scanner0.getAccuracy());
  }

  @Test
  public void test7()  throws Throwable  {
      Scanner scanner0 = new Scanner(11.13106742151496);
      RelativeAngle relativeAngle0 = scanner0.getScanArc();
      assertEquals(0.19634954084936207, relativeAngle0.getRadians(), 0.01D);
      assertNotNull(relativeAngle0);
  }
}
