/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.gui;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.awt.HeadlessException;
import javax.swing.JMenu;
import net.virtualinfinity.atrobots.gui.Main;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class ArenaWindowBuilderEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Main main0 = new Main();
      // Undeclared exception!
      try {
        main0.initializeWindow();
        fail("Expecting exception: HeadlessException");
      } catch(HeadlessException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      Main main0 = new Main();
      JMenu jMenu0 = main0.createViewMenu();
      assertEquals(7, jMenu0.getMenuComponentCount());
      assertEquals("View", jMenu0.getText());
      assertNotNull(jMenu0);
  }
}
