/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.gui;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.util.Collection;
import net.virtualinfinity.atrobots.gui.ArenaPane;
import net.virtualinfinity.atrobots.gui.ArenaRenderer;
import net.virtualinfinity.atrobots.gui.RobotStatusPane;
import net.virtualinfinity.atrobots.gui.renderers.SnapshotRenderer;
import net.virtualinfinity.atrobots.snapshots.ArenaObjectSnapshot;
import net.virtualinfinity.atrobots.snapshots.ExplosionSnapshot;
import net.virtualinfinity.atrobots.snapshots.MineSnapshot;
import net.virtualinfinity.atrobots.snapshots.MissileSnapshot;
import net.virtualinfinity.atrobots.snapshots.RobotSnapshot;
import net.virtualinfinity.atrobots.snapshots.ScanSnapshot;

@RunWith(EvoSuiteRunner.class)
public class ArenaRendererEvoSuiteTest {


  //Test case number: 0
  /*
   * 3 covered goals:
   * 1 net.virtualinfinity.atrobots.gui.ArenaRenderer.setMineRenderer(Lnet/virtualinfinity/atrobots/gui/renderers/SnapshotRenderer;)V: root-Branch
   * 2 net.virtualinfinity.atrobots.gui.ArenaRenderer.getRobotRenderer()Lnet/virtualinfinity/atrobots/gui/renderers/SnapshotRenderer;: root-Branch
   * 3 net.virtualinfinity.atrobots.gui.ArenaRenderer.<init>()V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      ArenaRenderer arenaRenderer0 = new ArenaRenderer();
      SnapshotRenderer<? super RobotSnapshot> snapshotRenderer0 = arenaRenderer0.getRobotRenderer();
      arenaRenderer0.setMineRenderer(snapshotRenderer0);
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 net.virtualinfinity.atrobots.gui.ArenaRenderer.setHints(Ljava/awt/RenderingHints;)V: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      ArenaRenderer arenaRenderer0 = new ArenaRenderer();
      arenaRenderer0.setHints((RenderingHints) null);
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 net.virtualinfinity.atrobots.gui.ArenaRenderer.getMissileRenderer()Lnet/virtualinfinity/atrobots/gui/renderers/SnapshotRenderer;: root-Branch
   */
  @Test
  public void test2()  throws Throwable  {
      ArenaRenderer arenaRenderer0 = new ArenaRenderer();
      SnapshotRenderer<? super MissileSnapshot> snapshotRenderer0 = arenaRenderer0.getMissileRenderer();
      assertNotNull(snapshotRenderer0);
  }

  //Test case number: 3
  /*
   * 2 covered goals:
   * 1 net.virtualinfinity.atrobots.gui.ArenaRenderer.setExplosionRenderer(Lnet/virtualinfinity/atrobots/gui/renderers/SnapshotRenderer;)V: root-Branch
   * 2 net.virtualinfinity.atrobots.gui.ArenaRenderer.getExplosionRenderer()Lnet/virtualinfinity/atrobots/gui/renderers/SnapshotRenderer;: root-Branch
   */
  @Test
  public void test3()  throws Throwable  {
      ArenaPane arenaPane0 = new ArenaPane();
      ArenaRenderer arenaRenderer0 = arenaPane0.getArenaRenderer();
      SnapshotRenderer<? super ExplosionSnapshot> snapshotRenderer0 = arenaRenderer0.getExplosionRenderer();
      arenaRenderer0.setExplosionRenderer(snapshotRenderer0);
  }

  //Test case number: 4
  /*
   * 1 covered goal:
   * 1 net.virtualinfinity.atrobots.gui.ArenaRenderer.setScanRenderer(Lnet/virtualinfinity/atrobots/gui/renderers/SnapshotRenderer;)V: root-Branch
   */
  @Test
  public void test4()  throws Throwable  {
      ArenaRenderer arenaRenderer0 = new ArenaRenderer();
      SnapshotRenderer<? super RobotSnapshot> snapshotRenderer0 = arenaRenderer0.getRobotRenderer();
      arenaRenderer0.setScanRenderer(snapshotRenderer0);
  }

  //Test case number: 5
  /*
   * 1 covered goal:
   * 1 net.virtualinfinity.atrobots.gui.ArenaRenderer.setToPaint(Ljava/util/Collection;)V: root-Branch
   */
  @Test
  public void test5()  throws Throwable  {
      ArenaPane arenaPane0 = new ArenaPane();
      ArenaRenderer arenaRenderer0 = arenaPane0.getArenaRenderer();
      arenaRenderer0.setToPaint((Collection<ArenaObjectSnapshot>) null);
  }

  //Test case number: 6
  /*
   * 1 covered goal:
   * 1 net.virtualinfinity.atrobots.gui.ArenaRenderer.getScanRenderer()Lnet/virtualinfinity/atrobots/gui/renderers/SnapshotRenderer;: root-Branch
   */
  @Test
  public void test6()  throws Throwable  {
      ArenaRenderer arenaRenderer0 = new ArenaRenderer();
      SnapshotRenderer<? super ScanSnapshot> snapshotRenderer0 = arenaRenderer0.getScanRenderer();
      assertNotNull(snapshotRenderer0);
  }

  //Test case number: 7
  /*
   * 2 covered goals:
   * 1 net.virtualinfinity.atrobots.gui.ArenaRenderer.setMissileRenderer(Lnet/virtualinfinity/atrobots/gui/renderers/SnapshotRenderer;)V: root-Branch
   * 2 net.virtualinfinity.atrobots.gui.ArenaRenderer.getExplosionRenderer()Lnet/virtualinfinity/atrobots/gui/renderers/SnapshotRenderer;: root-Branch
   */
  @Test
  public void test7()  throws Throwable  {
      ArenaPane arenaPane0 = new ArenaPane();
      ArenaRenderer arenaRenderer0 = arenaPane0.getArenaRenderer();
      SnapshotRenderer<? super ExplosionSnapshot> snapshotRenderer0 = arenaRenderer0.getExplosionRenderer();
      arenaRenderer0.setMissileRenderer(snapshotRenderer0);
  }

  //Test case number: 8
  /*
   * 1 covered goal:
   * 1 net.virtualinfinity.atrobots.gui.ArenaRenderer.drawBorder(Ljava/awt/Graphics2D;)V: root-Branch
   */
  @Test
  public void test8()  throws Throwable  {
      ArenaRenderer arenaRenderer0 = new ArenaRenderer();
      // Undeclared exception!
      try {
        arenaRenderer0.drawBorder((Graphics2D) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  //Test case number: 9
  /*
   * 1 covered goal:
   * 1 net.virtualinfinity.atrobots.gui.ArenaRenderer.getMineRenderer()Lnet/virtualinfinity/atrobots/gui/renderers/SnapshotRenderer;: root-Branch
   */
  @Test
  public void test9()  throws Throwable  {
      ArenaPane arenaPane0 = new ArenaPane();
      ArenaRenderer arenaRenderer0 = arenaPane0.getArenaRenderer();
      SnapshotRenderer<? super MineSnapshot> snapshotRenderer0 = arenaRenderer0.getMineRenderer();
      assertNotNull(snapshotRenderer0);
  }

  //Test case number: 10
  /*
   * 1 covered goal:
   * 1 net.virtualinfinity.atrobots.gui.ArenaRenderer.setRobotStatusPane(Lnet/virtualinfinity/atrobots/gui/RobotStatusPane;)V: root-Branch
   */
  @Test
  public void test10()  throws Throwable  {
      ArenaRenderer arenaRenderer0 = new ArenaRenderer();
      RobotStatusPane robotStatusPane0 = RobotStatusPane.createRobotStatusPane();
      arenaRenderer0.setRobotStatusPane(robotStatusPane0);
      assertEquals(false, robotStatusPane0.isDoubleBuffered());
  }

  //Test case number: 11
  /*
   * 1 covered goal:
   * 1 net.virtualinfinity.atrobots.gui.ArenaRenderer.getHints()Ljava/awt/RenderingHints;: root-Branch
   */
  @Test
  public void test11()  throws Throwable  {
      ArenaRenderer arenaRenderer0 = new ArenaRenderer();
      RenderingHints renderingHints0 = arenaRenderer0.getHints();
      assertNotNull(renderingHints0);
      assertEquals("{Global antialiasing enable key=Antialiased rendering mode}", renderingHints0.toString());
  }

  //Test case number: 12
  /*
   * 2 covered goals:
   * 1 net.virtualinfinity.atrobots.gui.ArenaRenderer.setRobotRenderer(Lnet/virtualinfinity/atrobots/gui/renderers/SnapshotRenderer;)V: root-Branch
   * 2 net.virtualinfinity.atrobots.gui.ArenaRenderer.getRobotRenderer()Lnet/virtualinfinity/atrobots/gui/renderers/SnapshotRenderer;: root-Branch
   */
  @Test
  public void test12()  throws Throwable  {
      ArenaRenderer arenaRenderer0 = new ArenaRenderer();
      SnapshotRenderer<? super RobotSnapshot> snapshotRenderer0 = arenaRenderer0.getRobotRenderer();
      arenaRenderer0.setRobotRenderer(snapshotRenderer0);
  }

  //Test case number: 13
  /*
   * 3 covered goals:
   * 1 net.virtualinfinity.atrobots.gui.ArenaRenderer.innerPaint(Ljava/awt/Graphics2D;)V: I4 Branch 1 IFNE L29 - false
   * 2 net.virtualinfinity.atrobots.gui.ArenaRenderer.hasFullFrame()Z: I4 Branch 3 IFNULL L96 - true
   * 3 net.virtualinfinity.atrobots.gui.ArenaRenderer.<init>()V: root-Branch
   */
  @Test
  public void test13()  throws Throwable  {
      ArenaPane arenaPane0 = new ArenaPane();
      ArenaRenderer arenaRenderer0 = arenaPane0.getArenaRenderer();
      arenaRenderer0.innerPaint((Graphics2D) null);
  }
}
