/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.gui;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.awt.Graphics;
import net.virtualinfinity.atrobots.arena.SimulationFrameBuffer;
import net.virtualinfinity.atrobots.gui.ArenaPane;
import net.virtualinfinity.atrobots.gui.ArenaRenderer;
import net.virtualinfinity.atrobots.gui.RobotStatusPane;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class ArenaPaneEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ArenaPane arenaPane0 = new ArenaPane();
      arenaPane0.frameAvailable((SimulationFrameBuffer) null);
      assertEquals("ComponentUI", arenaPane0.getUIClassID());
  }

  @Test
  public void test1()  throws Throwable  {
      ArenaPane arenaPane0 = new ArenaPane();
      // Undeclared exception!
      try {
        arenaPane0.reset();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class javax.swing.RepaintManager
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      ArenaPane arenaPane0 = new ArenaPane();
      ArenaRenderer arenaRenderer0 = arenaPane0.getArenaRenderer();
      assertNotNull(arenaRenderer0);
  }

  @Test
  public void test3()  throws Throwable  {
      ArenaPane arenaPane0 = new ArenaPane();
      arenaPane0.setRobotStatusPane((RobotStatusPane) null);
      assertEquals(false, arenaPane0.isValidateRoot());
  }

  @Test
  public void test4()  throws Throwable  {
      ArenaPane arenaPane0 = new ArenaPane();
      // Undeclared exception!
      try {
        arenaPane0.paintComponent((Graphics) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test5()  throws Throwable  {
      ArenaPane arenaPane0 = new ArenaPane();
      arenaPane0.setOpaque(true);
      // Undeclared exception!
      try {
        arenaPane0.paintComponent((Graphics) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
