/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.gui;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.awt.HeadlessException;
import net.virtualinfinity.atrobots.gui.Main;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class MainEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Main main0 = new Main();
      // Undeclared exception!
      try {
        main0.buildMenuBar();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      Main main0 = new Main();
      // Undeclared exception!
      try {
        main0.registerCloseListener();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test2()  throws Throwable  {
      Main main0 = new Main();
      main0.isDebugMode();
      assertEquals(true, main0.isPaused());
  }

  @Test
  public void test3()  throws Throwable  {
      Main main0 = new Main();
      // Undeclared exception!
      try {
        main0.run();
        fail("Expecting exception: HeadlessException");
      } catch(HeadlessException e) {
      }
  }

  @Test
  public void test4()  throws Throwable  {
      Main main0 = new Main();
      assertEquals(true, main0.isPaused());
      
      main0.setPaused(false);
      assertEquals(false, main0.isPaused());
  }

  @Test
  public void test5()  throws Throwable  {
      Main main0 = new Main();
      main0.setDebugMode(true);
      assertEquals(true, main0.isDebugMode());
  }

  @Test
  public void test6()  throws Throwable  {
      Main main0 = new Main();
      boolean boolean0 = main0.isPaused();
      assertEquals(true, boolean0);
  }
}
