/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.hardware.transponder;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.hardware.transponder.Transponder;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TransponderEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Transponder transponder0 = new Transponder();
      int int0 = transponder0.getId();
      assertEquals(0, int0);
  }

  @Test
  public void test1()  throws Throwable  {
      Transponder transponder0 = new Transponder();
      transponder0.setId(172);
      assertEquals(172, transponder0.getId());
  }
}
