/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.gui.renderers;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.awt.Graphics2D;
import java.util.Set;
import java.util.TreeSet;
import net.virtualinfinity.atrobots.gui.renderers.MineRenderer;
import net.virtualinfinity.atrobots.snapshots.MineSnapshot;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class MineRendererEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      MineRenderer mineRenderer0 = new MineRenderer();
      MineSnapshot mineSnapshot0 = new MineSnapshot();
      TreeSet<Integer> treeSet0 = new TreeSet<Integer>();
      // Undeclared exception!
      try {
        mineRenderer0.render((Graphics2D) null, mineSnapshot0, (Set<Integer>) treeSet0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
