/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.gui.renderers;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.awt.Graphics2D;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.TreeSet;
import net.virtualinfinity.atrobots.gui.renderers.MissileRenderer;
import net.virtualinfinity.atrobots.measures.Duration;
import net.virtualinfinity.atrobots.snapshots.MissileSnapshot;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class MissileRendererEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      MissileRenderer missileRenderer0 = new MissileRenderer();
      MissileSnapshot missileSnapshot0 = new MissileSnapshot(false, (Duration) null);
      HashSet<Integer> hashSet0 = new HashSet<Integer>();
      // Undeclared exception!
      try {
        missileRenderer0.render((Graphics2D) null, missileSnapshot0, (Set<Integer>) hashSet0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      Duration duration0 = Duration.fromCycles(579);
      MissileSnapshot missileSnapshot0 = new MissileSnapshot(true, duration0);
      LinkedHashSet<Integer> linkedHashSet0 = new LinkedHashSet<Integer>();
      MissileRenderer missileRenderer0 = new MissileRenderer();
      // Undeclared exception!
      try {
        missileRenderer0.render((Graphics2D) null, missileSnapshot0, (Set<Integer>) linkedHashSet0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test2()  throws Throwable  {
      MissileRenderer missileRenderer0 = new MissileRenderer();
      Duration duration0 = Duration.ONE_CYCLE;
      MissileSnapshot missileSnapshot0 = new MissileSnapshot(true, duration0);
      TreeSet<Integer> treeSet0 = new TreeSet<Integer>();
      // Undeclared exception!
      try {
        missileRenderer0.render((Graphics2D) null, missileSnapshot0, (Set<Integer>) treeSet0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
