/*
 * This file was automatically generated by EvoSuite
 */

package net.virtualinfinity.atrobots.radio;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.virtualinfinity.atrobots.hardware.radio.Transceiver;
import net.virtualinfinity.atrobots.radio.RadioDispatcher;
import net.virtualinfinity.atrobots.radio.RadioListener;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class RadioDispatcherEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      RadioDispatcher radioDispatcher0 = new RadioDispatcher();
      Transceiver transceiver0 = new Transceiver();
      radioDispatcher0.addRadioListener((RadioListener) transceiver0);
      radioDispatcher0.dispatch((RadioListener) transceiver0, 1567, (short)603);
      assertEquals(0, transceiver0.getChannel());
  }

  @Test
  public void test1()  throws Throwable  {
      RadioDispatcher radioDispatcher0 = new RadioDispatcher();
      Transceiver transceiver0 = new Transceiver();
      radioDispatcher0.dispatch((RadioListener) transceiver0, 890, (short)1);
      assertEquals(0, transceiver0.getChannel());
  }
}
